#!/usr/bin/env python3
"""Record a CI benchmark and rebuild the repository benchmark report."""

from __future__ import annotations

import argparse
import html
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


RATE_RE = re.compile(r"^builder facade: ([0-9]+) operations/s$", re.MULTILINE)
SIZE_RE = re.compile(
    r"^representative monomorphised binary: ([0-9]+) bytes$", re.MULTILINE
)


@dataclass(frozen=True)
class Result:
    pr: int
    commit: str
    recorded_at: str
    operations_per_second: int
    binary_bytes: int

    @classmethod
    def from_dict(cls, value: dict[str, object]) -> "Result":
        return cls(
            pr=int(value["pr"]),
            commit=str(value["commit"]),
            recorded_at=str(value["recorded_at"]),
            operations_per_second=int(value["operations_per_second"]),
            binary_bytes=int(value["binary_bytes"]),
        )


def parse_log(log: str) -> tuple[int, int]:
    rate = RATE_RE.search(log)
    size = SIZE_RE.search(log)
    if rate is None or size is None:
        raise ValueError("benchmark output did not contain both expected metrics")
    return int(rate.group(1)), int(size.group(1))


def load_results(results_root: Path) -> list[Result]:
    results = []
    for path in results_root.glob("pr-*/result.json"):
        results.append(Result.from_dict(json.loads(path.read_text(encoding="utf-8"))))
    return sorted(results, key=lambda result: result.pr)


def render_svg(results: list[Result]) -> str:
    width, height = 800, 260
    left, right, top, bottom = 70, 25, 25, 45
    plot_width = width - left - right
    plot_height = height - top - bottom
    rates = [result.operations_per_second for result in results]
    maximum = max(rates, default=1)
    minimum = min(rates, default=0)
    padding = max((maximum - minimum) * 0.1, maximum * 0.05, 1)
    low, high = max(0, minimum - padding), maximum + padding

    def point(index: int, rate: int) -> tuple[float, float]:
        x = left + (plot_width / max(len(results) - 1, 1)) * index
        y = top + plot_height * (high - rate) / (high - low)
        return x, y

    points = [point(index, rate) for index, rate in enumerate(rates)]
    polyline = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    dots = "\n".join(
        f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="4"><title>PR #{result.pr}: '
        f'{result.operations_per_second:,} operations/s</title></circle>'
        for (x, y), result in zip(points, results)
    )
    labels = "\n".join(
        f'  <text x="{x:.1f}" y="{height - 18}" text-anchor="middle">#{result.pr}</text>'
        for (x, _), result in zip(points, results)
    )
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">
  <title id="title">Historical builder facade benchmark</title>
  <desc id="desc">Operations per second for retained pull request benchmark results.</desc>
  <style>text {{ font: 12px sans-serif; fill: #57606a }} .axis {{ stroke: #8c959f }} polyline {{ fill: none; stroke: #0969da; stroke-width: 2 }} circle {{ fill: #0969da }}</style>
  <line class="axis" x1="{left}" y1="{top}" x2="{left}" y2="{height - bottom}"/>
  <line class="axis" x1="{left}" y1="{height - bottom}" x2="{width - right}" y2="{height - bottom}"/>
  <text x="12" y="{top + plot_height / 2:.1f}" transform="rotate(-90 12 {top + plot_height / 2:.1f})" text-anchor="middle">operations/s</text>
  <text x="{left - 8}" y="{top + 4}" text-anchor="end">{round(high):,}</text>
  <text x="{left - 8}" y="{height - bottom + 4}" text-anchor="end">{round(low):,}</text>
  <polyline points="{polyline}"/>
{dots}
{labels}
</svg>
"""


def render_markdown(results: list[Result]) -> str:
    rows = "\n".join(
        f"| [#{result.pr}](https://github.com/freshtonic/pg-proto/pull/{result.pr}) "
        f"| `{html.escape(result.commit[:12])}` | {html.escape(result.recorded_at)} "
        f"| {result.operations_per_second:,} | {result.binary_bytes:,} |"
        for result in results
    )
    if not rows:
        rows = "| — | — | — | — | — |"
    return f"""# Benchmark history

This report is generated by `scripts/update_benches.py`. Each pull request retains
one result, which is replaced when that pull request's benchmarks run again.

![Historical builder facade benchmark](benchmark-results/history.svg)

| Pull request | Commit | Recorded (UTC) | Builder operations/s | Binary bytes |
| ---: | :--- | :--- | ---: | ---: |
{rows}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=Path, required=True)
    parser.add_argument("--pr", type=int, required=True)
    parser.add_argument("--commit", required=True)
    parser.add_argument("--recorded-at")
    parser.add_argument("--results-root", type=Path, default=Path("benchmark-results"))
    parser.add_argument("--report", type=Path, default=Path("BENCHES.md"))
    args = parser.parse_args()

    rate, size = parse_log(args.log.read_text(encoding="utf-8"))
    recorded_at = args.recorded_at or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    result = Result(args.pr, args.commit, recorded_at, rate, size)
    result_dir = args.results_root / f"pr-{args.pr}"
    result_dir.mkdir(parents=True, exist_ok=True)
    (result_dir / "result.json").write_text(
        json.dumps(result.__dict__, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    results = load_results(args.results_root)
    (args.results_root / "history.svg").write_text(render_svg(results), encoding="utf-8")
    args.report.write_text(render_markdown(results), encoding="utf-8")


if __name__ == "__main__":
    main()
