name: Release-plz

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    name: Publish releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install development Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.97.1

      - name: Publish release
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-pr:
    name: Prepare release pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install development Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.97.1

      - name: Prepare release pull request
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
